export const BOGO_ELIGIBLE_PRODUCTS = {
  "Margherita": ["med"],
  "Italian margherita": ["med"],
  "Crunchy veggie": ["med"],
  "Veggie d-lights": ["med"],
  "Golden sweet corn": ["med"],
  "Paneer tikka pizza": ["med"],
  "Hawaiian pizza": ["med"],
  "Caribbean pizza": ["med"],
  "Soya chaap pizza": ["med"],
  "Italian sweet": ["med"],
  "Heat 'n sweet": ["med"],
  "Hot stuff": ["med"],
  "Garlic to hot": ["med"],
  "Four season": ["med"],
  "Super spicy": ["med"],
  "Love in box (heart shape)": ["med"],
  "Cheese pizza": ["med"],
  "Chicago spl paneer": ["med"],
  "Peri peri boom": ["med"],
  "Mughlai retreat": ["med"],
  "Karahi paneer pizza": ["med"],
  "Makhni supreme": ["med"],
  "7 veggies": ["med"],
  "Mexican overload": ["med"],
  "Tandoori paneer": ["med"],
  "Cheese pasta pizza": ["med"],
  "Spicy pasta pizza": ["med"],
  "Chicago’s flood pizza": ["med"],
  "Bursty cheese pizza": ["med"],
};